data_ingestion_config:
dataset_url : "dileep070/heart-disease-prediction-using-logistic-regression"
raw_data_dir : raw_data
ingested_dir : ingested_data
ingested_train_dir : train
ingested_test_dir : test