training_pipeline_config:
  pipeline_name: heart_risk_analyzer
  artifact_dir: artifact

data_ingestion_config:
  dataset_url : "dileep070/heart-disease-prediction-using-logistic-regression"
  zip_data_dir : "zip_data_dir"
  zip_file_name : "heart-disease-prediction-using-logistic-regression.zip"
  raw_data_dir : raw_data
  ingested_dir : ingested_data
  ingested_train_dir : train
  ingested_test_dir : test

data_validation_config:
  schema_dir : config
  schema_file_name : schema.yaml
  report_file_name : report.json
  report_page_file_name : report.html

data_transformation_config:
  change_feature_male_to_gender : gender
  transformed_dir : transformed_dir
  transformed_test_dir: test
  transformed_train_dir: train
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  convert_features_to_objects: true