grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2

model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      C : 1.0
    search_param_grid:
      penalty:
      - l1
      - l2
      C:
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
      solver:
      - newton-cg
      - lbfgs
      - liblinear
      - sag
      - saga
      max_iter:
      - 100
      - 200
      - 500
      - 1000
      class_weigth:
      - None
      - balanced

  module_1:
    class: GaussianNB
    module: sklearn.naive_bayes
    params:
      priors:
      - None
    search_param_grid:
      var_smoothing:
      - 1e-2
      - 1e-3
      - 1e-4
      - 1e-5
      - 1e-6
      - 1e-7
      - 1e-8
      - 1e-9
      - 1e-10
      - 1e-11
      - 1e-12
      - 1e-13
      - 1e-14
      - 1e-15